version = 1
SPDX-PackageName = "btp-object-store"
SPDX-PackageSupplier = "Jagadeshwar Rao Anem (jagadeshwar.rao.anem@sap.com)"
SPDX-PackageDownloadLocation = "https://github.com/sap-docs/btp-object-store"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and SAP-docs/btp-object-store contributors"
SPDX-License-Identifier = "CC-BY-4.0"
